<?php
// This file is part of Moodle - http://moodle.org/

/**
 * English language strings for CDexamSave.
 *
 * @package    quizaccess_cdexamsave
 * @copyright  2026 Carlos Díaz Bueno <carlosdiazbueno@gmail.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'CDexamSave focus monitoring';
$string['formheader'] = 'CDexamSave: focus monitoring';
$string['enabled'] = 'Enable focus monitoring';
$string['enabled_help'] = 'Records when the quiz tab or window stops being active. Authorised staff can follow incidents in a near-real-time report.';
$string['warnstudent'] = 'Warn the student after an incident';
$string['warnstudent_help'] = 'When the student returns to the quiz, show a clear notice that the focus change was recorded.';
$string['graceperiod'] = 'Ignore changes shorter than';
$string['graceperiod_help'] = 'Very short focus changes can be generated by browser or operating-system controls. This grace period reduces accidental incidents.';
$string['grace_none'] = 'Do not ignore any change';
$string['grace_halfsecond'] = '0.5 seconds';
$string['grace_onesecond'] = '1 second';
$string['grace_twoseconds'] = '2 seconds';
$string['grace_threeseconds'] = '3 seconds';
$string['invalidgraceperiod'] = 'Select a valid grace period.';
$string['monitoringnotice'] = 'CDexamSave monitoring is enabled. Leaving this quiz tab or window will be recorded and reported to authorised staff.';
$string['monitoringbadge'] = 'Focus monitoring active';
$string['studentwarningtitle'] = 'Focus change recorded';
$string['studentwarningtext'] = 'This quiz stopped being the active window. The incident has been added to the teacher’s live report.';
$string['studentwarningduration'] = 'Time away: {$a}';
$string['continueattempt'] = 'Continue the quiz';
$string['openlivereport'] = 'Open CDexamSave live report';

$string['settingsheading'] = 'CDexamSave';
$string['settingsheading_desc'] = 'Site-wide performance and retention settings. Monitoring is enabled separately in each quiz.';
$string['retentiondays'] = 'Retention period (days)';
$string['retentiondays_desc'] = 'Completed incident and session data older than this is deleted by the scheduled cleanup task. Minimum effective value: 1 day.';
$string['reportrefresh'] = 'Live report refresh (seconds)';
$string['reportrefresh_desc'] = 'Polling interval for the teacher report. Values are limited to 2–30 seconds.';
$string['heartbeatinterval'] = 'Student heartbeat (seconds)';
$string['heartbeatinterval_desc'] = 'How often an active attempt confirms that its monitoring script is connected. Values are limited to 5–60 seconds.';
$string['staleseconds'] = 'Disconnected threshold (seconds)';
$string['staleseconds_desc'] = 'An attempt is shown as disconnected after this period without a heartbeat. Values are limited to 15–300 seconds.';
$string['maxincidents'] = 'Maximum incidents per attempt';
$string['maxincidents_desc'] = 'Safety limit that prevents a malfunctioning or manipulated browser from filling the database. Values are limited to 100–10000.';

$string['cdexamsave:viewreport'] = 'View the CDexamSave live report';
$string['cdexamsave:exportreport'] = 'Export CDexamSave incident data';

$string['livereport'] = 'CDexamSave live report';
$string['reportfor'] = 'Focus monitoring: {$a}';
$string['reportintro'] = 'The panel refreshes automatically and lists all in-progress attempts plus the most recent focus-loss incidents.';
$string['reportdisabled'] = 'CDexamSave is not currently enabled in this quiz.';
$string['live'] = 'Live';
$string['paused'] = 'Paused';
$string['lastupdated'] = 'Last updated: {$a}';
$string['refreshnow'] = 'Refresh now';
$string['pauserefresh'] = 'Pause automatic refresh';
$string['resumerefresh'] = 'Resume automatic refresh';
$string['enablenotifications'] = 'Enable browser alerts';
$string['notificationsenabled'] = 'Browser alerts enabled';
$string['notificationsdenied'] = 'Browser alerts blocked';
$string['notificationtitle'] = 'CDexamSave: new focus incident';
$string['notificationbody'] = '{$a->student} — {$a->reason}';
$string['exportcsv'] = 'Export all incidents (CSV)';
$string['activeattempts'] = 'Active attempts';
$string['attentionnow'] = 'Focus currently lost';
$string['connectedattempts'] = 'Connected';
$string['totalincidents'] = 'Incidents';
$string['participants'] = 'In-progress attempts';
$string['recentincidents'] = 'Recent incidents';
$string['student'] = 'Student';
$string['attempt'] = 'Attempt';
$string['connection'] = 'Connection';
$string['focusstate'] = 'Focus state';
$string['incidentcount'] = 'Incidents';
$string['totaltimeaway'] = 'Total time away';
$string['lastheartbeat'] = 'Last signal';
$string['status_connected'] = 'Connected';
$string['status_attention'] = 'Outside Moodle';
$string['status_disconnected'] = 'No recent signal';
$string['status_notstarted'] = 'Connecting';
$string['focus_ok'] = 'Active';
$string['focus_lost'] = 'Focus lost';
$string['none'] = 'None';
$string['noactiveattempts'] = 'There are no in-progress attempts.';
$string['noincidents'] = 'No focus-loss incidents have been recorded.';
$string['started'] = 'Started';
$string['ended'] = 'Returned';
$string['duration'] = 'Duration';
$string['reason'] = 'Detection';
$string['incidentactive'] = 'In progress';
$string['reason_visibility_hidden'] = 'Tab hidden';
$string['reason_window_blur'] = 'Window lost focus';
$string['reason_pagehide'] = 'Page closed or hidden';
$string['reason_freeze'] = 'Page suspended';
$string['reason_unknown'] = 'Focus change';
$string['pollerror'] = 'The live data could not be updated. CDexamSave will retry automatically.';
$string['noscript'] = 'JavaScript is required to display the live report.';
$string['privacywarning'] = 'This report contains personal assessment-monitoring data. Handle exported files according to your centre’s data-protection policy.';

$string['export_student'] = 'Student';
$string['export_userid'] = 'User ID';
$string['export_attempt'] = 'Attempt';
$string['export_started'] = 'Focus lost';
$string['export_returned'] = 'Focus returned';
$string['export_duration'] = 'Duration (seconds)';
$string['export_reason'] = 'Detection';
$string['export_active'] = 'Still active';
$string['yes'] = 'Yes';
$string['no'] = 'No';

$string['taskcleanup'] = 'Delete expired CDexamSave monitoring data';
$string['invalidrequest'] = 'Invalid CDexamSave monitoring request.';
$string['monitoringdisabled'] = 'CDexamSave monitoring is not enabled for this quiz.';
$string['attemptnotmonitorable'] = 'This attempt cannot be monitored.';
$string['incidentlimitreached'] = 'The incident safety limit for this attempt has been reached.';
$string['invalidgroup'] = 'You cannot view data for that group.';

$string['privacy:metadata:quizaccess_cdexamsave_evt'] = 'Focus-loss incidents detected during monitored quiz attempts.';
$string['privacy:metadata:quizaccess_cdexamsave_evt:quizid'] = 'The monitored quiz.';
$string['privacy:metadata:quizaccess_cdexamsave_evt:attemptid'] = 'The monitored quiz attempt.';
$string['privacy:metadata:quizaccess_cdexamsave_evt:userid'] = 'The student whose attempt was monitored.';
$string['privacy:metadata:quizaccess_cdexamsave_evt:eventuuid'] = 'A random identifier used to prevent duplicate incidents.';
$string['privacy:metadata:quizaccess_cdexamsave_evt:pagesessionid'] = 'A random identifier for the browser monitoring session.';
$string['privacy:metadata:quizaccess_cdexamsave_evt:reason'] = 'The browser signal that detected the focus change.';
$string['privacy:metadata:quizaccess_cdexamsave_evt:times'] = 'Server and client timestamps and incident duration.';
$string['privacy:metadata:quizaccess_cdexamsave_sess'] = 'The current monitoring connection state for a quiz attempt.';
$string['privacy:metadata:quizaccess_cdexamsave_sess:quizid'] = 'The monitored quiz.';
$string['privacy:metadata:quizaccess_cdexamsave_sess:attemptid'] = 'The monitored quiz attempt.';
$string['privacy:metadata:quizaccess_cdexamsave_sess:userid'] = 'The student whose attempt was monitored.';
$string['privacy:metadata:quizaccess_cdexamsave_sess:pagesessionid'] = 'A random identifier for the browser monitoring session.';
$string['privacy:metadata:quizaccess_cdexamsave_sess:state'] = 'Connection, focus and heartbeat state.';
$string['privacy:path'] = 'CDexamSave focus monitoring';
