<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English language strings for CD Exam Control.
 *
 * @package    quizaccess_cdexamcontrol
 * @copyright  2026 Carlos Díaz Bueno
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['activeattempts'] = 'Active attempts';
$string['attempt'] = 'Attempt';
$string['attemptnotmonitorable'] = 'This attempt cannot be monitored.';
$string['attentionnow'] = 'Focus currently lost';
$string['blockshortcuts_help'] = 'Attempts to prevent Ctrl/Cmd+T, Ctrl/Cmd+N and links opening another tab where the browser allows it. Off by default. Does not block operating-system shortcuts, clipboard, zoom or assistive technology.';
$string['blockshortcuts'] = 'Restrict new tabs and windows';
$string['cdexamcontrol:exempt'] = 'Exempt an individual from CD Exam Control for an agreed adjustment';
$string['cdexamcontrol:exportreport'] = 'Export CD Exam Control incident data';
$string['cdexamcontrol:viewreport'] = 'View the CD Exam Control live report';
$string['collectorbusy'] = 'The collector is busy. The browser will retry this observation.';
$string['connectedattempts'] = 'Connected';
$string['connection'] = 'Connection';
$string['continueattempt'] = 'Continue the quiz';
$string['duration'] = 'Duration';
$string['enabled_help'] = 'Records when the quiz tab or window stops being active. Authorised staff can follow incidents in a near-real-time report.';
$string['enabled'] = 'Enable focus monitoring';
$string['enablenotifications'] = 'Enable browser alerts';
$string['ended'] = 'Returned';
$string['export_active'] = 'Still active';
$string['export_attempt'] = 'Attempt';
$string['export_duration'] = 'Duration (seconds)';
$string['export_finish'] = 'Finished';
$string['export_incidentcount'] = 'Incident count';
$string['export_maxduration'] = 'Longest incident (seconds)';
$string['export_needsreview'] = 'Review priority';
$string['export_reason'] = 'Detection';
$string['export_returned'] = 'Focus returned';
$string['export_start'] = 'Started';
$string['export_started'] = 'Focus lost';
$string['export_state'] = 'Attempt state';
$string['export_student'] = 'Student';
$string['export_totalduration'] = 'Total time away (seconds)';
$string['export_userid'] = 'User ID';
$string['exportincidentscsv'] = 'Detailed incidents (CSV)';
$string['exportsummarycsv'] = 'Attempt summary (CSV)';
$string['filterall'] = 'All in-progress attempts';
$string['filterattention'] = 'Focus currently lost';
$string['filterdisconnected'] = 'No recent signal';
$string['filterlabel'] = 'Filter attempts';
$string['filterreview'] = 'Review recommended';
$string['focus_lost'] = 'Focus lost';
$string['focus_ok'] = 'Active';
$string['focusstate'] = 'Focus state';
$string['formheader'] = 'CD Exam Control';
$string['fullscreenbutton'] = 'Enter fullscreen and continue';
$string['fullscreenerror'] = 'Fullscreen could not be entered. Retry or ask your teacher to adjust the quiz settings.';
$string['fullscreentext'] = 'This quiz requests fullscreen. Exiting it may create a browser observation. Use the button to return. Your answers and the Moodle timer remain under Moodle control.';
$string['fullscreentitle'] = 'Return to the quiz in fullscreen';
$string['fullscreenunsupported'] = 'This browser cannot provide fullscreen. You can continue with focus monitoring; tell your teacher about this limitation.';
$string['grace_halfsecond'] = '0.5 seconds';
$string['grace_none'] = 'Do not ignore any change';
$string['grace_onesecond'] = '1 second';
$string['grace_threeseconds'] = '3 seconds';
$string['grace_twoseconds'] = '2 seconds';
$string['graceperiod_help'] = 'Very short focus changes can be generated by browser or operating-system controls. This grace period reduces accidental incidents.';
$string['graceperiod'] = 'Ignore changes shorter than';
$string['heartbeatinterval_desc'] = 'How often an active attempt confirms that its monitoring script is connected. Values are limited to 5–60 seconds.';
$string['heartbeatinterval'] = 'Student heartbeat (seconds)';
$string['incidentactive'] = 'In progress';
$string['incidentcount'] = 'Incidents';
$string['incidentlimitreached'] = 'The incident safety limit for this attempt has been reached.';
$string['invalidgraceperiod'] = 'Select a valid grace period.';
$string['invalidgroup'] = 'You cannot view data for that group.';
$string['invalidrequest'] = 'Invalid CD Exam Control monitoring request.';
$string['lastheartbeat'] = 'Last signal';
$string['lastupdated'] = 'Last updated: {$a}';
$string['live'] = 'Live';
$string['livereport'] = 'CD Exam Control live report';
$string['maxincidents_desc'] = 'Safety limit that prevents a malfunctioning or manipulated browser from filling the database. Values are limited to 100–10000.';
$string['maxincidents'] = 'Maximum incidents per attempt';
$string['monitorconnecting'] = 'CD Exam Control connecting';
$string['monitoringbadge'] = 'CD Exam Control connected';
$string['monitoringdisabled'] = 'CD Exam Control monitoring is not enabled for this quiz.';
$string['monitoringnotice'] = 'CD Exam Control is enabled. Browser focus changes and configured exam controls are reported to authorised staff. Technical or accessibility issues can cause observations; staff must interpret them in context.';
$string['monitorpending'] = 'CD Exam Control: observations pending connection';
$string['monitorqueuefull'] = 'CD Exam Control: too many pending observations; tell your teacher.';
$string['monitorstopped'] = 'CD Exam Control: monitoring stopped';
$string['no'] = 'No';
$string['noactiveattempts'] = 'There are no in-progress attempts.';
$string['nofilteredattempts'] = 'No in-progress attempts match the current search and filter.';
$string['noincidents'] = 'No focus-loss incidents have been recorded.';
$string['none'] = 'None';
$string['noscript'] = 'JavaScript is required to display the live report.';
$string['notificationbody'] = '{$a->student} — {$a->reason}';
$string['notificationsdenied'] = 'Browser alerts blocked';
$string['notificationsenabled'] = 'Browser alerts enabled';
$string['notificationtitle'] = 'CD Exam Control: new focus incident';
$string['openlivereport'] = 'Open CD Exam Control live report';
$string['participants'] = 'In-progress attempts';
$string['paused'] = 'Paused';
$string['pauserefresh'] = 'Pause automatic refresh';
$string['pluginname'] = 'CD Exam Control';
$string['pollerror'] = 'The live data could not be updated. CD Exam Control will retry automatically.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt:attemptid'] = 'The monitored quiz attempt.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt:eventuuid'] = 'A random identifier used to prevent duplicate incidents.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt:pagesessionid'] = 'A random identifier for the browser monitoring session.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt:quizid'] = 'The monitored quiz.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt:reason'] = 'The browser signal that detected the focus change.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt:times'] = 'Server and client timestamps and incident duration.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt:userid'] = 'The student whose attempt was monitored.';
$string['privacy:metadata:quizaccess_cdexamcontrol_evt'] = 'Focus-loss incidents detected during monitored quiz attempts.';
$string['privacy:metadata:quizaccess_cdexamcontrol_ses:attemptid'] = 'The monitored quiz attempt.';
$string['privacy:metadata:quizaccess_cdexamcontrol_ses:pagesessionid'] = 'A random identifier for the browser monitoring session.';
$string['privacy:metadata:quizaccess_cdexamcontrol_ses:quizid'] = 'The monitored quiz.';
$string['privacy:metadata:quizaccess_cdexamcontrol_ses:state'] = 'Connection, focus and heartbeat state.';
$string['privacy:metadata:quizaccess_cdexamcontrol_ses:userid'] = 'The student whose attempt was monitored.';
$string['privacy:metadata:quizaccess_cdexamcontrol_ses'] = 'The current monitoring connection state for a quiz attempt.';
$string['privacy:path'] = 'CD Exam Control focus monitoring';
$string['privacywarning'] = 'This report contains personal assessment-monitoring data. Handle exported files according to your centre’s data-protection policy.';
$string['reason_freeze'] = 'Page suspended';
$string['reason_fullscreen_exit'] = 'Fullscreen exited';
$string['reason_pagehide'] = 'Page closed or hidden';
$string['reason_shortcut_blocked'] = 'New tab or window request intercepted';
$string['reason_unknown'] = 'Focus change';
$string['reason_visibility_hidden'] = 'Tab hidden';
$string['reason_window_blur'] = 'Window lost focus';
$string['reason'] = 'Detection';
$string['recentincidents'] = 'Recent incidents';
$string['refreshnow'] = 'Refresh now';
$string['reportdisabled'] = 'CD Exam Control is not currently enabled in this quiz.';
$string['reportfor'] = 'Focus monitoring: {$a}';
$string['reportintro'] = 'The panel lists in-progress attempts and recent browser observations. Durations are estimates and connection failures can delay observations.';
$string['reportrefresh_desc'] = 'Polling interval for the teacher report. Values are limited to 2–30 seconds.';
$string['reportrefresh'] = 'Live report refresh (seconds)';
$string['requirefullscreen_help'] = 'Displays an accessible fullscreen prompt. A browser that lacks fullscreen can continue with focus monitoring. This is a browser aid, not a secure kiosk. Disable it for accessibility adjustments where appropriate.';
$string['requirefullscreen'] = 'Request fullscreen during the attempt';
$string['resumerefresh'] = 'Resume automatic refresh';
$string['retentiondays_desc'] = 'Completed incident and session data older than this is deleted by the scheduled cleanup task. Minimum effective value: 1 day.';
$string['retentiondays'] = 'Retention period (days)';
$string['reviewdisclaimer'] = 'Review priority is a configurable triage aid based on incident count and cumulative duration. It is not proof of misconduct and each attempt must be interpreted in context.';
$string['reviewduration_desc'] = 'Prioritise an attempt after its cumulative time away reaches this value. Values are limited to 1–86400 seconds.';
$string['reviewduration'] = 'Review duration threshold (seconds)';
$string['reviewincidentcount_desc'] = 'Prioritise an attempt after it reaches this number of incidents. Values are limited to 1–100.';
$string['reviewincidentcount'] = 'Review incident threshold';
$string['reviewnotneeded'] = 'No priority';
$string['reviewpriority'] = 'Review priority';
$string['reviewprioritysettings_desc'] = 'These thresholds help staff triage attempts. They do not determine or imply misconduct.';
$string['reviewprioritysettings'] = 'Human review priority';
$string['reviewrecommended'] = 'Review recommended';
$string['searchattempts'] = 'Search students';
$string['searchattemptsplaceholder'] = 'Search by student name';
$string['settingsheading_desc'] = 'Site-wide performance and retention settings. Monitoring is enabled separately in each quiz.';
$string['settingsheading'] = 'CD Exam Control';
$string['shortcutnotice'] = 'This quiz restricts opening another tab or window.';
$string['staleseconds_desc'] = 'An attempt is shown as disconnected after this period without a heartbeat. Values are limited to 15–300 seconds.';
$string['staleseconds'] = 'Disconnected threshold (seconds)';
$string['started'] = 'Started';
$string['status_attention'] = 'Quiz focus lost';
$string['status_connected'] = 'Connected';
$string['status_disconnected'] = 'No recent signal';
$string['status_exempt'] = 'Agreed adjustment: monitoring exempt';
$string['status_notstarted'] = 'Connecting';
$string['student'] = 'Student';
$string['studentwarningduration'] = 'Time away: {$a}';
$string['studentwarningtext'] = 'This quiz stopped being active or left fullscreen. A browser observation will be sent to authorised staff. It does not establish misconduct.';
$string['studentwarningtitle'] = 'Quiz focus changed';
$string['taskcleanup'] = 'Delete expired CD Exam Control monitoring data';
$string['totalincidents'] = 'Incidents';
$string['totaltimeaway'] = 'Total time away';
$string['warnstudent_help'] = 'When the student returns to the quiz, show a clear notice that the focus change was recorded.';
$string['warnstudent'] = 'Warn the student after an incident';
$string['yes'] = 'Yes';
